"""
Django settings for mfv_mis project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATE_DIRS = (
    BASE_DIR + '/templates/',

)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'EDFdjango-insecure-b#)@prod=a+k#m%%u^$#qqcyh+fvl42s%7^w1hzm4+l=1l44a7x%1b912mfvstg34'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'import_export',
    'mis',
    'application_master',
    'dashboard',
    'reports',
    'survey',
    'rest_framework',
    'export_data',
    'send_mail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mfv_mis.middleware.CheckPreviousMonthDataSubmissionMiddleware',
]

ROOT_URLCONF = 'mfv_mis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/templates/',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mfv_mis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       'NAME': 'raahi_nov13',
#       'NAME': 'mfv_uat_25jul24',
       'USER': 'postgres',
#       'PASSWORD': 'Mfv@Mis@081222',
        'PASSWORD': 'Loga@589',
       'HOST': 'localhost',
       'PORT': '',
       'AUTOCOMMIT': True,
   }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata' #'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

PROJECT_ENV = "/home/mfvuser/mfvmis_staging_venv"

STATIC_URL = '/static/'

STATICFILES_DIRS = (BASE_DIR + '/static/',)

#Managing Media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL  = '/media/'


STATIC_ROOT = os.path.join(BASE_DIR, 'assests')
STATICFILES_DIR = [
os.path.join(BASE_DIR, 'static')
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1500 # higher than the count of fields
INSTANCE_CACHE_PREFIX = "MFV_DEV__"


# Settings related to SYNC apis

SYNC_SETTINGS = {
    # responses api version v1
    'RESPONSES_V1': {
        # number of records to send in each api call - page size
        'BATCH_SIZE': 400
    },
    # responses api version v3
    'RESPONSES_V3': {
        # number of records to send in each api call - page size
        'BATCH_SIZE': 800
    }
}

BLEACH_VALID_TAGS = ['p', 'b', 'i', 'strike', 'ul', 'li', 'ol', 'br',
                    'span', 'blockquote', 'hr', 'a', 'img']
BLEACH_VALID_ATTRS = {
   'span': ['style', ],
   'p': ['align', ],
   'a': ['href', 'rel'],
   'img': ['src', 'alt', 'style'],
}
BLEACH_VALID_STYLES = ['color', 'cursor', 'float', 'margin']



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':50
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
        "LOCATION": "127.0.0.1:11211",
        'DEFAULT_SHORT_DURATION': 86400000,
    }
}

LOGGING = {
    'version': 1,
    'asyncio': {
        'level': 'WARNING',
    },
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)-8s %(asctime)s %(process)d %(thread)d %(module)s %(message)s',
        },
    },
    'handlers': {
        'log_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': "/home/logavanan-a/Desktop/Django/Raahi/raahi_dev/media/log/error.log",
            'formatter': 'verbose'
        },
    },
    'loggers': {
        '': {
            'handlers': ['log_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'level': 'DEBUG',
        },
    }
}

APP_CONFIG={"app_code": "MFVUI", "is_gps_madatory": 0, "training_module": {}, "is_tile_required": 1, "can_show_category": 0, "is_draft_required": 1, "is_filter_reqired": 1, "can_show_empty_ans": 1, "is_search_required": 1, "is_traning_required": 0, "can_show_periodicity": 1, "can_continue_activity": 0, "can_show_question_code": 0, "is_summary_view_required": 1, "is_project_module_required": 1, "is_activity_module_required": 1, "is_beneficiary_module_reuired": 1, "can_show_activity_in_direct_flow": 1,"APP_URL":""}

EXPORT_MEDIA_URL = 'https://mfvdev.tsbcloud.in/export_data/file-download/'


# Config for the export data
EXPORT_CSV = {
    # Sleep time between each survey export
    'SLEEP_TIME_SECONDS': 0,
    # Connect timout is in seconds
    'CONNECT_TIMEOUT_BUILD': 0,
    'CONNECT_TIMEOUT_FETCH': 0

}

DATE_DISPLAY_FORMAT='%d/%m/%Y'
MONTH_DISPLAY_FORMAT='%m/%Y'

WEBPAGINATIONPAGECOUNT=10
PAGE_NUMBER_DISPLAY_COUNT = 5

RESPONSE_IMPORT = {
    "PROCESSED_FILE_PATH":'/media/import-response/processed_files/',
    "WEB_IMPORT_CHUNK_SIZE" : 2,
    "MAX_FILE_SIZE" : 1 * 1024 * 1024,  # 10 MB
    "unique_id" : {
        "1": "235", # mobile number
    },
    "FILE_PERMISSION_COMMAND": "chown sb:www-data {0}",
}

MEDIA_DIR = BASE_DIR + '/media'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mfvprogramme@missionforvision.org.in'
EMAIL_HOST_PASSWORD = 'rtny ijkv ucus rrog'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

DASHBOARD_SUBMISSION_DAY = 6 

APP_EMAIL_SETTINGS = {
    # For Testing purpose Add the flag as "Test" else "LIVE"

    'MODE': 'LIVE',  # LIVE/TEST

    # All mails are sent only to the test_mail_list  when mode = 'TEST'

    'TEST_MAIL_LIST': ['yuvaraj.kharvi@thesocialbytes.com'],

    # No of times have tried to send email on faliure

    'MAX_ATTEMPTS': 2,
    # No of emails picked on every attempt

    'BATCH_SIZE': 50,
}

PERFORMANCE_TRACKER_TEMPLATES = BASE_DIR + '/static/performance_tracker_templates'

HOST_URL = "https://mfvdev.tsbcloud.in"

ACTIVITY_MAIL_RECIEVER = ['yuvaraj.kharvi@thesocialbytes.com','vishwanath.bailwad@thesocialbytes.com']
APP_URL = "https://drive.google.com/file/d/13JOe775A_IFDoMuepm2TxvYO-uXDSCQf/view?usp=drive_link"