# Generated by Django 3.2.4 on 2022-10-12 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('html_template', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mail Template',
            },
        ),
        migrations.CreateModel(
            name='MailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('mail_to', models.TextField()),
                ('mail_cc', models.TextField(blank=True, null=True)),
                ('mail_bcc', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(1, 'high'), (2, 'normal')], default=2)),
                ('send_attempt', models.PositiveIntegerField(default=0)),
                ('time_last_attempt', models.DateField(blank=True, null=True)),
                ('mail_status', models.IntegerField(choices=[(1, 'new'), (2, 'makedToSend'), (3, 'Sent'), (4, 'Failed'), (5, 'Ingnored')], default=1)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('mode', models.TextField(blank=True, null=True)),
                ('file_paths', models.JSONField(default=list, help_text="file info should be in this format [ {'file_path':'example path','file_type':'text','filename':'example.text'}] ")),
                ('template_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='send_mail.mailtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
