# Generated by Django 4.2.2 on 2023-07-11 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maildata',
            old_name='created',
            new_name='server_created_on',
        ),
        migrations.RenameField(
            model_name='maildata',
            old_name='modified',
            new_name='server_modified_on',
        ),
        migrations.RenameField(
            model_name='mailtemplate',
            old_name='created',
            new_name='server_created_on',
        ),
        migrations.RenameField(
            model_name='mailtemplate',
            old_name='modified',
            new_name='server_modified_on',
        ),
        migrations.RemoveField(
            model_name='maildata',
            name='active',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='active',
        ),
        migrations.AddField(
            model_name='maildata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maildata',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maildata',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AddField(
            model_name='maildata',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='maildata',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maildata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
