# Generated by Django 4.2.2 on 2023-07-11 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_mail', '0002_rename_created_maildata_server_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
