# Generated by Django 4.2.2 on 2023-08-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_alter_mailtemplate_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildata',
            name='file_paths',
            field=models.JSONField(blank=True, default=list, help_text="file info should be in this format [ {'file_path':'example path','file_type':'text','filename':'example.text'}] ", null=True),
        ),
    ]
