# Generated by Django 4.2.1 on 2023-12-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0004_alter_maildata_file_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maildata',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='maildata',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
    ]
