# Generated by Django 4.2.1 on 2023-12-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0005_remove_maildata_uuid_remove_mailtemplate_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildata',
            name='syn_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
