# Generated by Django 4.2.1 on 2024-01-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0007_maildata_error_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildata',
            name='client_mail_bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildata',
            name='client_mail_cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildata',
            name='client_mail_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
