# Generated by Django 4.2.1 on 2024-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0008_maildata_client_mail_bcc_maildata_client_mail_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildata',
            name='cron_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildata',
            name='cron_mail_bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildata',
            name='cron_mail_cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildata',
            name='cron_mail_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildata',
            name='syn_mail_bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildata',
            name='syn_mail_cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildata',
            name='syn_mail_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
