# Generated by Django 5.0 on 2024-03-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_chartmeta_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidgetsummarylog',
            name='error',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardwidgetsummarylog',
            name='most_recent_update_time_taken_millis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
