# Generated by Django 4.2.1 on 2023-09-04 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MprIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MPR Indicator',
            },
        ),
        migrations.CreateModel(
            name='TruckerMprData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('partner_id', models.IntegerField(default=0)),
                ('vision_center_id', models.IntegerField(default=0)),
                ('donor_id', models.IntegerField(default=0)),
                ('partner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('vision_center_name', models.CharField(blank=True, max_length=150, null=True)),
                ('donor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('indicator_month', models.CharField(blank=True, max_length=150, null=True)),
                ('indicator_year', models.CharField(blank=True, max_length=150, null=True)),
                ('male_target', models.IntegerField(default=0)),
                ('female_target', models.IntegerField(default=0)),
                ('total_target', models.IntegerField(default=0)),
                ('current_month_achievement_male', models.IntegerField(default=0)),
                ('current_month_achievement_female', models.IntegerField(default=0)),
                ('current_month_achievement_total', models.IntegerField(default=0)),
                ('till_date_achievement', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('mpr_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.mprindicator')),
            ],
            options={
                'verbose_name_plural': 'Trucker MPR Data',
            },
        ),
    ]
