# Generated by Django 4.2.1 on 2023-09-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_truckermpr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruckerMpr',
        ),
    ]
