# Generated by Django 4.2.1 on 2023-10-09 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_truckermpr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckermpr',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='server_created_on',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='server_modified_on',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='status',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='sync_status',
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('export_status', models.IntegerField(choices=[(1, 'Not Downloaded'), (2, 'Downloaded')], db_index=True, default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reports.reportmeta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Report Export',
            },
        ),
    ]
