# Generated by Django 4.2.1 on 2023-10-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_truckermpr_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexport',
            name='export_status',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Yes')]),
        ),
    ]
