# Generated by Django 4.2.1 on 2023-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_reportexport_export_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprindicator',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='reportexport',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='reportmeta',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='truckermprdata',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending')], db_index=True, default=2),
        ),
    ]
