# Generated by Django 4.2.1 on 2023-12-19 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0048_district_ssmis_id_donor_ssmis_id_partner_ssmis_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0009_alter_mprindicator_status_alter_reportexport_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('year', models.IntegerField(default=0)),
                ('code', models.IntegerField(default=0)),
                ('tracket_col_1', models.IntegerField(default=0)),
                ('tracket_col_2', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.partner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
