# Generated by Django 5.0 on 2023-12-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_reporttracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprindicator',
            name='ssmis_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
