# Generated by Django 4.2.1 on 2023-12-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_mprindicator_ssmis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckermprdata',
            name='district_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermprdata',
            name='four_column_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermprdata',
            name='one_column_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermprdata',
            name='state_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermprdata',
            name='three_column_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermprdata',
            name='two_column_value',
            field=models.IntegerField(default=0),
        ),
    ]
