# Generated by Django 4.2.1 on 2024-02-08 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0012_truckermprdata_district_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MprStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('mpr_report_code', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Pending for Approval'), (2, 'Zonal Coordinator Approved'), (3, 'Zonal Coordinator Rejected'), (4, 'PPA Approved'), (5, 'PPA Rejected'), (6, 'National Coordinator Approved'), (7, 'National Coordinator Rejected'), (8, 'Super Admin Approved'), (9, 'Super Admin Rejected')], default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('partner_date', models.DateTimeField(blank=True, null=True)),
                ('zonal_coordinator_date', models.DateTimeField(blank=True, null=True)),
                ('ppa_date', models.DateTimeField(blank=True, null=True)),
                ('national_coordinator_date', models.DateTimeField(blank=True, null=True)),
                ('super_admin_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
