# Generated by Django 4.2.1 on 2024-02-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0015_mprstatusupdate_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprstatusupdate',
            name='forward_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forward_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
