# Generated by Django 4.2.1 on 2024-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_mprstatusupdate_forward_to_super_admin_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprstatusupdate',
            name='national_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
