# Generated by Django 4.2.1 on 2024-02-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_mprstatusupdate_national_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprstatusupdate',
            name='super_admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
