# Generated by Django 4.2.1 on 2024-02-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_mprstatusupdate_super_admin_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprstatusupdate',
            name='forward_nc_command',
            field=models.TextField(blank=True, null=True),
        ),
    ]
