# Generated by Django 4.2.1 on 2024-02-26 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0020_mprstatusupdate_forward_nc_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprstatusupdate',
            name='ssims_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ssims_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
