# Generated by Django 4.2.1 on 2024-02-29 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0056_visioncenter_vc_type'),
        ('reports', '0021_mprstatusupdate_ssims_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprstatusupdate',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.partner'),
        ),
    ]
