# Generated by Django 5.0 on 2024-02-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_mprstatusupdate_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckermpr',
            name='mpr_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Pending for Approval'), (2, 'Zonal Coordinator Approved'), (3, 'Zonal Coordinator Rejected'), (4, 'PPA Approved'), (5, 'PPA Rejected'), (6, 'National Coordinator Approved'), (7, 'National Coordinator Rejected'), (8, 'Super Admin Approved'), (9, 'Super Admin Rejected')], default=0),
        ),
    ]
