# Generated by Django 5.0 on 2024-03-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_truckermpr_mpr_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruckerMpr',
        ),
    ]
