# Generated by Django 5.0 on 2024-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_alter_truckermpr_i_10_indi_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckermpr',
            name='camp_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truckermpr',
            name='district_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truckermpr',
            name='donor_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truckermpr',
            name='partner_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truckermpr',
            name='ssmis_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truckermpr',
            name='state_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truckermpr',
            name='zone_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
