# Generated by Django 4.2.1 on 2024-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_alter_truckermpr_camp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckermpr',
            name='i_77_achive_female',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_77_achive_male',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_77_achive_till_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_77_achive_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_77_indi_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_77_metric_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_78_achive_female',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_78_achive_male',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_78_achive_till_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_78_achive_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_78_indi_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_78_metric_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_79_achive_female',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_79_achive_male',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_79_achive_till_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_79_achive_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_79_indi_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='truckermpr',
            name='i_79_metric_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
