# Generated by Django 4.2.1 on 2024-03-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_truckermpr_i_77_achive_female_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckermpr',
            name='i_79_achive_female',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='i_79_achive_male',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='i_79_achive_till_date',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='i_79_achive_total',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='i_79_indi_code',
        ),
        migrations.RemoveField(
            model_name='truckermpr',
            name='i_79_metric_code',
        ),
    ]
