# Generated by Django 4.2.1 on 2023-06-13 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0010_remove_vendor_created_by_remove_vendor_district_and_more'),
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrequest',
            options={'verbose_name_plural': 'Order Requests'},
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='approved_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.partner'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
