# Generated by Django 4.2.1 on 2023-06-13 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_vendor_partnervendorlinkage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sims', '0003_product_orderrequestdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrequest',
            options={},
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='approved_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.partner'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=150),
        ),
    ]
