# Generated by Django 4.2.1 on 2023-06-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0004_alter_orderrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Submit for Approval'), (3, 'Approved'), (4, 'Cancelled')], null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
    ]
