# Generated by Django 4.2.1 on 2023-06-15 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sims', '0005_orderrequest_order_status_alter_orderrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrequest',
            options={'verbose_name_plural': 'Order Request'},
        ),
        migrations.AlterModelOptions(
            name='orderrequestdetails',
            options={'verbose_name_plural': 'Order Request Details'},
        ),
        migrations.CreateModel(
            name='OrderDeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('received_quantity', models.PositiveIntegerField()),
                ('damaged_quantity', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sims.orderrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sims.product')),
            ],
            options={
                'verbose_name_plural': 'Order Delivery Details',
            },
        ),
    ]
