# Generated by Django 4.2.1 on 2023-06-19 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_alter_orderrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequestdetails',
            name='damaged_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequestdetails',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
