# Generated by Django 4.2.1 on 2023-06-19 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_userpartnerlinkage'),
        ('sims', '0007_alter_orderrequest_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.partner'),
        ),
    ]
