# Generated by Django 4.2.1 on 2023-06-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0008_alter_orderrequest_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequestdetails',
            name='damaged_quantity',
        ),
        migrations.RemoveField(
            model_name='orderrequestdetails',
            name='received_quantity',
        ),
    ]
