# Generated by Django 4.2.1 on 2023-06-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_userpartnerlinkage'),
        ('sims', '0009_remove_orderrequestdetails_damaged_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='uuid',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='vision_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.visioncenter'),
        ),
    ]
