# Generated by Django 4.2.1 on 2023-06-22 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0012_userpartnerlinkage'),
        ('sims', '0011_alter_orderrequest_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('village', models.CharField(blank=True, max_length=150, null=True)),
                ('block', models.CharField(blank=True, max_length=150, null=True)),
                ('expected_glass_prescription', models.CharField(blank=True, max_length=150, null=True)),
                ('expected_refer_surgeries', models.CharField(blank=True, max_length=150, null=True)),
                ('expected_camp_OPD', models.CharField(blank=True, max_length=150, null=True)),
                ('coordinator_name', models.CharField(blank=True, max_length=150, null=True)),
                ('coordinator_mobile_no', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.district')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.donor')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Camp',
            },
        ),
    ]
