# Generated by Django 4.2.1 on 2023-06-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0013_alter_camp_coordinator_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestdetails',
            name='rrv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
