# Generated by Django 4.2.1 on 2023-06-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0014_orderrequestdetails_rrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sims.camp'),
        ),
    ]
