# Generated by Django 4.2.1 on 2023-06-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0015_orderrequest_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='order_for',
            field=models.IntegerField(blank=True, choices=[(1, 'Vision Center'), (2, 'Camp')], null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='shippment_address',
            field=models.IntegerField(blank=True, choices=[(1, 'Partner'), (2, 'Camp'), (3, 'Other')], null=True),
        ),
    ]
