# Generated by Django 4.2.1 on 2023-06-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0016_orderrequest_order_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequestdetails',
            name='order_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sims.orderrequest'),
        ),
        migrations.AlterField(
            model_name='orderrequestdetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sims.product'),
        ),
    ]
