# Generated by Django 4.2.1 on 2023-06-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0017_alter_orderrequestdetails_order_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestdetails',
            name='frame_type',
            field=models.IntegerField(blank=True, choices=[(1, 'R2CCM015'), (2, 'R2CCM021')], null=True),
        ),
    ]
