# Generated by Django 4.2.1 on 2023-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0018_orderrequestdetails_frame_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='other_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
