# Generated by Django 4.2.1 on 2023-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0021_orderrequest_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequestdetails',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
