# Generated by Django 4.2.1 on 2023-07-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0022_alter_orderrequestdetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequestdetails',
            name='rrv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
