# Generated by Django 4.2.1 on 2023-07-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0023_alter_orderrequestdetails_rrv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequestdetails',
            name='rrv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
