# Generated by Django 4.2.1 on 2023-07-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0024_alter_orderrequestdetails_rrv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Submited for Approval'), (3, 'Approved'), (4, 'Rejected'), (5, 'Shipped')], null=True),
        ),
    ]
