# Generated by Django 4.2.1 on 2023-07-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_userpartnerlinkage'),
        ('sims', '0025_alter_orderrequest_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='vision_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.visioncenter'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='shippment_address',
            field=models.IntegerField(blank=True, choices=[(1, 'Partner'), (2, 'Camp'), (3, 'Other'), (4, 'Vision Center')], null=True),
        ),
    ]
