# Generated by Django 4.2.1 on 2023-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0026_camp_vision_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverydetails',
            name='rrv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdeliverydetails',
            name='damaged_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdeliverydetails',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
