# Generated by Django 4.2.1 on 2023-07-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0027_orderdeliverydetails_rrv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverydetails',
            name='frame_type',
            field=models.IntegerField(blank=True, choices=[(1, 'R2CCM015'), (2, 'R2CCM021')], null=True),
        ),
    ]
