# Generated by Django 4.2.1 on 2023-07-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0028_orderdeliverydetails_frame_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='approved_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
