# Generated by Django 4.2.1 on 2023-07-17 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0022_rename_slug_masterlookup_parent_and_more'),
        ('sims', '0029_orderrequest_remark_alter_orderrequest_approved_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(db_index=True, max_length=150, unique=True)),
                ('unique_id', models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True)),
                ('patient_id', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Third gender')], null=True)),
                ('contact_no_1', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_no_2', models.CharField(blank=True, max_length=150, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('taluk', models.CharField(max_length=150)),
                ('aadhaar_pan_no', models.CharField(blank=True, max_length=150, null=True)),
                ('drivers_license_no', models.CharField(blank=True, max_length=150, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('time_since_driving', models.CharField(blank=True, max_length=150, null=True)),
                ('do_you_have_a_life_insurance_policy', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('do_you_have_a_vehicle_insurance_policy', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('do_you_have_a_health_insurance_policy', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('others', models.CharField(blank=True, max_length=150, null=True)),
                ('no_of_months_employed_in_a_year', models.CharField(blank=True, max_length=150, null=True)),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='caste', to='master_data.masterlookup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.district')),
                ('educational_qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='educational_qualification', to='master_data.masterlookup')),
                ('how_do_you_know_about_camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='how_do_you_know_about_camp', to='master_data.masterlookup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('monthly_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monthly_income', to='master_data.masterlookup')),
                ('residence_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='residence_type', to='master_data.masterlookup')),
                ('type_of_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_of_job', to='master_data.masterlookup')),
                ('type_of_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_of_route', to='master_data.masterlookup')),
                ('type_of_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_of_vehicle', to='master_data.masterlookup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
