# Generated by Django 4.2.1 on 2023-07-17 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_alter_masterlookup_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sims', '0030_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='do_you_have_a_health_insurance_policy',
            new_name='health_insurance_policy',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='do_you_have_a_life_insurance_policy',
            new_name='life_insurance_policy',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='do_you_have_a_vehicle_insurance_policy',
            new_name='vehicle_insurance_policy',
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(db_index=True, max_length=150, unique=True)),
                ('patient_uuid', models.CharField(db_index=True, max_length=150)),
                ('blood_pressure', models.CharField(blank=True, max_length=150, null=True)),
                ('blood_sugar', models.CharField(blank=True, max_length=150, null=True)),
                ('weight', models.CharField(blank=True, max_length=150, null=True)),
                ('height', models.CharField(blank=True, max_length=150, null=True)),
                ('family_details', models.TextField(blank=True, null=True)),
                ('total_family_members', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_holding_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('alter_employment', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('learn_alter_livelihood_skill', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('family_support_financially', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('medical_checkup_past_1_year', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('diabetes', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('hypertension', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('smoke', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('alcohol', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('eye_examination', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('seeing_distant_objects', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('judging_distance_while_driving', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('traffic_colors', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('seeing_while_night_driving', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('wear_glasses_ever', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('wearing_glasses_currently', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('nearby_hospital', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('accident_while_driving_commercial_vehicle_before', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('accident_vehicle_in_last_twelve_months', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('first_aid_kit', models.IntegerField(blank=True, choices=[(0, 'NA'), (1, 'YES'), (2, 'NO')], null=True)),
                ('if_you_are_happy_specify_in_what_way', models.CharField(blank=True, max_length=150, null=True)),
                ('code_description', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_description', to='master_data.masterlookup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('employed_in_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employed_in_year', to='master_data.masterlookup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('non_working_months', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='non_working_months', to='master_data.masterlookup')),
                ('salary_calculated', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salary_calculated', to='master_data.masterlookup')),
                ('type_of_hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_of_hospital', to='master_data.masterlookup')),
                ('you_happy_with_your_profession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profession', to='master_data.masterlookup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
