# Generated by Django 4.2.1 on 2023-07-20 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0024_district_sync_status_donor_sync_status_and_more'),
        ('sims', '0031_rename_do_you_have_a_health_insurance_policy_patient_health_insurance_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='orderdeliverydetails',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='orderrequestdetails',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='app_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='app_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='screening',
            name='app_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='app_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='VisualAcuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(db_index=True, max_length=150, unique=True)),
                ('screening_uuid', models.CharField(db_index=True, max_length=150)),
                ('do_you_want_to_refer', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('app_created_at', models.DateTimeField(blank=True, null=True)),
                ('app_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('aided_distance_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aided_distance_le', to='master_data.masterlookup')),
                ('aided_distance_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aided_distance_re', to='master_data.masterlookup')),
                ('aided_near_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aided_near_le', to='master_data.masterlookup')),
                ('aided_near_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aided_near_re', to='master_data.masterlookup')),
                ('color_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_le', to='master_data.masterlookup')),
                ('color_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_re', to='master_data.masterlookup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('pinhole_distance_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pinhole_distance_le', to='master_data.masterlookup')),
                ('pinhole_distance_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pinhole_distance_re', to='master_data.masterlookup')),
                ('pinhole_near_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pinhole_near_le', to='master_data.masterlookup')),
                ('pinhole_near_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pinhole_near_re', to='master_data.masterlookup')),
                ('refer_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refer_for', to='master_data.masterlookup')),
                ('refer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refer_to', to='master_data.masterlookup')),
                ('treatment_for_refraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='treatment_for_refraction', to='master_data.masterlookup')),
                ('unaided_distance_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unaided_distance_le', to='master_data.masterlookup')),
                ('unaided_distance_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unaided_distance_re', to='master_data.masterlookup')),
                ('unaided_near_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unaided_near_le', to='master_data.masterlookup')),
                ('unaided_near_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unaided_near_re', to='master_data.masterlookup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
