# Generated by Django 4.2.1 on 2023-07-21 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0024_district_sync_status_donor_sync_status_and_more'),
        ('sims', '0032_camp_sync_status_orderdeliverydetails_sync_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(db_index=True, max_length=150, unique=True)),
                ('patient_uuid', models.CharField(db_index=True, max_length=150)),
                ('sph_distance_re', models.CharField(blank=True, max_length=150, null=True)),
                ('sph_distance_le', models.CharField(blank=True, max_length=150, null=True)),
                ('cyl_distance_re', models.CharField(blank=True, max_length=150, null=True)),
                ('cyl_distance_le', models.CharField(blank=True, max_length=150, null=True)),
                ('axis_distance_re', models.CharField(blank=True, max_length=150, null=True)),
                ('axis_distance_le', models.CharField(blank=True, max_length=150, null=True)),
                ('sph_near_re', models.CharField(blank=True, max_length=150, null=True)),
                ('sph_near_le', models.CharField(blank=True, max_length=150, null=True)),
                ('cyl_near_re', models.CharField(blank=True, max_length=150, null=True)),
                ('cyl_near_le', models.CharField(blank=True, max_length=150, null=True)),
                ('axis_near_re', models.CharField(blank=True, max_length=150, null=True)),
                ('axis_near_le', models.CharField(blank=True, max_length=150, null=True)),
                ('near_has_the_glass_collected', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('r2c_has_the_glass_collected', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('custom_has_the_glass_collected', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('app_created_at', models.DateTimeField(blank=True, null=True)),
                ('app_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('custom_frame_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_frame_code', to='master_data.masterlookup')),
                ('custom_frame_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_frame_size', to='master_data.masterlookup')),
                ('custom_glass_collecting_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_glass_collecting_location', to='master_data.state')),
                ('custom_lens_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_lens_type', to='master_data.masterlookup')),
                ('custom_model_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_model_type', to='master_data.masterlookup')),
                ('custom_type_of_coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_type_of_coating', to='master_data.masterlookup')),
                ('custom_vision_center_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_glass_collecting_location', to='master_data.visioncenter')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('near_frame_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='near_frame_code', to='master_data.masterlookup')),
                ('near_frame_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='near_frame_size', to='master_data.masterlookup')),
                ('near_glass_collecting_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='near_glass_collecting_location', to='master_data.state')),
                ('near_lens_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='near_lens_type', to='master_data.masterlookup')),
                ('near_model_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='near_model_type', to='master_data.masterlookup')),
                ('near_type_of_coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='near_type_of_coating', to='master_data.masterlookup')),
                ('near_vision_center_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='near_vision_center_name', to='master_data.visioncenter')),
                ('r2c_frame_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='r2c_frame_code', to='master_data.masterlookup')),
                ('r2c_frame_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='r2c_frame_size', to='master_data.masterlookup')),
                ('r2c_glass_collecting_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='r2c_glass_collecting_location', to='master_data.state')),
                ('r2c_lens_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='r2c_lens_type', to='master_data.masterlookup')),
                ('r2c_model_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='r2c_model_type', to='master_data.masterlookup')),
                ('r2c_type_of_coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='r2c_type_of_coating', to='master_data.masterlookup')),
                ('r2c_vision_center_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='r2c_vision_center_name', to='master_data.visioncenter')),
                ('spectacle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spectacle_type', to='master_data.masterlookup')),
                ('va_distance_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='va_distance_le', to='master_data.masterlookup')),
                ('va_distance_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='va_distance_re', to='master_data.masterlookup')),
                ('va_near_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='va_near_le', to='master_data.masterlookup')),
                ('va_near_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='va_near_re', to='master_data.masterlookup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
