# Generated by Django 4.2.1 on 2023-07-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0033_glassprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='awb_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
