# Generated by Django 4.2.1 on 2023-07-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0034_orderrequest_awb_no_orderrequest_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Submited for Approval'), (3, 'Approved'), (4, 'Rejected'), (5, 'Shipped'), (6, 'Received')], null=True),
        ),
    ]
