# Generated by Django 4.2.1 on 2023-07-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_remove_visioncenter_district'),
        ('sims', '0035_alter_orderrequest_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.donor'),
        ),
    ]
