# Generated by Django 4.2.1 on 2023-07-26 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_role_role_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sims', '0037_rename_patient_uuid_glassprescription_screening_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sims.camp'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.userprofile'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='accident_vehicle_in_last_twelve_months',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='accident_while_driving_commercial_vehicle_before',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='alcohol',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='alter_employment',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='diabetes',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='eye_examination',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='family_support_financially',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='first_aid_kit',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='hypertension',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='judging_distance_while_driving',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='learn_alter_livelihood_skill',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='medical_checkup_past_1_year',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='nearby_hospital',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='seeing_distant_objects',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='seeing_while_night_driving',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='smoke',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='traffic_colors',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='wear_glasses_ever',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='wearing_glasses_currently',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO'), (3, 'NA')], null=True),
        ),
        migrations.CreateModel(
            name='TellicallingQuestionsAndAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('receive_your_spectacles', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('ahmd_spectacles_received', models.CharField(blank=True, max_length=150, null=True)),
                ('currently_using_spectacles', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('satisfied_with_spectacle', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('any_problems_raised', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('satisfied_with_our_service', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('any_charges_while_collecting', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('rate_our_services', models.IntegerField(blank=True, choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Not so good'), (4, 'Average'), (5, 'Bad')], null=True)),
                ('ad', models.TextField(blank=True, null=True)),
                ('disposition_name', models.CharField(blank=True, max_length=150, null=True)),
                ('call_disposition_group', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
                ('agent_comments', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sims.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
