# Generated by Django 4.2.1 on 2023-07-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_role_role_slug'),
        ('sims', '0038_patient_camp_patient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellicallingquestionsandanswers',
            name='agent_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tellicallingquestionsandanswers',
            name='call_disposition_group',
            field=models.IntegerField(blank=True, choices=[(1, 'Complaint'), (2, 'Retry'), (3, 'Successful'), (4, 'UnSuccessful')], null=True),
        ),
        migrations.AlterField(
            model_name='tellicallingquestionsandanswers',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='master_data.masterlookup'),
        ),
        migrations.AlterField(
            model_name='tellicallingquestionsandanswers',
            name='disposition_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='disposition_name', to='master_data.masterlookup'),
        ),
    ]
