# Generated by Django 4.2.1 on 2023-07-27 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0030_role_role_slug'),
        ('sims', '0039_alter_tellicallingquestionsandanswers_agent_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CataractQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('referred_to_hospital_for_cataract', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('reason_for_cataract_no', models.CharField(blank=True, max_length=255, null=True)),
                ('visited_hospital', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('reason_for_visited_hospital_no', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_recomand_cataract_surgery', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('reason_for_hospital_recomand_cataract_surgery_no', models.CharField(blank=True, max_length=255, null=True)),
                ('undergo_surgery', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('reason_for_undergo_surgery_no', models.CharField(blank=True, max_length=255, null=True)),
                ('place_cataract_surgery', models.CharField(blank=True, max_length=255, null=True)),
                ('date_cataract_surgery', models.DateField(blank=True, null=True)),
                ('reason_for_notgone_cataract_surgery', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_free', models.IntegerField(blank=True, choices=[(1, 'Free'), (2, 'Subsidized'), (3, 'Paid')], null=True)),
                ('how_it_paid', models.IntegerField(blank=True, choices=[(1, 'Own Pocket'), (2, 'Insurences'), (3, 'Govt.Health Cards')], null=True)),
                ('improvement_vision', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('helpful_for_driving', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('beneficiary_feed_back', models.CharField(blank=True, max_length=255, null=True)),
                ('ad', models.TextField(blank=True, null=True)),
                ('call_disposition_group', models.IntegerField(blank=True, choices=[(1, 'Complaint'), (2, 'Retry'), (3, 'Successful'), (4, 'UnSuccessful')], null=True)),
                ('agent_comments', models.TextField(blank=True, null=True)),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cataract_comments', to='master_data.masterlookup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('disposition_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cataract_disposition', to='master_data.masterlookup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
