# Generated by Django 4.2.1 on 2023-07-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0040_cataractquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataractquestions',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sims.patient'),
        ),
        migrations.AddField(
            model_name='tellicallingquestionsandanswers',
            name='receiver_spectacles_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
