# Generated by Django 4.2.1 on 2023-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0041_cataractquestions_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='taluk',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
