# Generated by Django 4.2.1 on 2023-07-28 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0031_donor_code'),
        ('sims', '0042_alter_patient_taluk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='salary_calculated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salary_calculated', to='master_data.masterlookup'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='type_of_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_of_hospital', to='master_data.masterlookup'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='you_happy_with_your_profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profession', to='master_data.masterlookup'),
        ),
    ]
