# Generated by Django 4.2.1 on 2023-07-31 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0031_donor_code'),
        ('sims', '0043_alter_screening_salary_calculated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glassprescription',
            name='custom_frame_code',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='custom_frame_size',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='custom_glass_collecting_location',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='custom_has_the_glass_collected',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='custom_lens_type',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='custom_model_type',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='custom_type_of_coating',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='custom_vision_center_name',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='near_frame_code',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='near_frame_size',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='near_glass_collecting_location',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='near_has_the_glass_collected',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='near_lens_type',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='near_model_type',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='near_type_of_coating',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='near_vision_center_name',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='r2c_frame_code',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='r2c_frame_size',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='r2c_glass_collecting_location',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='r2c_has_the_glass_collected',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='r2c_lens_type',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='r2c_model_type',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='r2c_type_of_coating',
        ),
        migrations.RemoveField(
            model_name='glassprescription',
            name='r2c_vision_center_name',
        ),
        migrations.AlterField(
            model_name='glassprescription',
            name='spectacle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='glass_spectacle_type', to='master_data.masterlookup'),
        ),
        migrations.CreateModel(
            name='SpectacleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(db_index=True, max_length=150, unique=True)),
                ('glass_prescription_uuid', models.CharField(db_index=True, max_length=150)),
                ('spectacle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('has_the_glass_collected', models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True)),
                ('app_created_at', models.DateTimeField(blank=True, null=True)),
                ('app_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('frame_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='frame_code', to='master_data.masterlookup')),
                ('frame_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='frame_size', to='master_data.masterlookup')),
                ('glass_collecting_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.state')),
                ('lens_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lens_type', to='master_data.masterlookup')),
                ('model_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='near_model_type', to='master_data.masterlookup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('spectacle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spectacle_type', to='master_data.masterlookup')),
                ('type_of_coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_of_coating', to='master_data.masterlookup')),
                ('vision_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.visioncenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
