# Generated by Django 4.2.1 on 2023-08-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0044_remove_glassprescription_custom_frame_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassprescription',
            name='follow_up_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Ready'), (3, 'Delivered')], default=1, null=True),
        ),
    ]
