# Generated by Django 4.2.1 on 2023-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0045_alter_glassprescription_follow_up_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glassprescription',
            name='follow_up_status',
        ),
        migrations.AddField(
            model_name='spectacletype',
            name='follow_up_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Ready'), (3, 'Delivered')], default=1, null=True),
        ),
    ]
