# Generated by Django 4.2.1 on 2023-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0031_donor_code'),
        ('sims', '0046_remove_glassprescription_follow_up_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='employed_in_year',
        ),
        migrations.AddField(
            model_name='screening',
            name='employed_in_year',
            field=models.ManyToManyField(blank=True, to='master_data.masterlookup'),
        ),
    ]
