# Generated by Django 4.2.3 on 2023-08-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0048_camp_delay_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellicallingquestionsandanswers',
            name='impact_on_their_driving_after_wearing',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True),
        ),
    ]
