# Generated by Django 4.2.1 on 2023-08-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0049_tellicallingquestionsandanswers_impact_on_their_driving_after_wearing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='others',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='taluk',
        ),
    ]
