# Generated by Django 4.2.1 on 2023-08-14 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0031_donor_code'),
        ('sims', '0050_remove_patient_caste_remove_patient_others_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(db_index=True, max_length=150, unique=True)),
                ('screening_uuid', models.CharField(db_index=True, max_length=150)),
                ('patient_uuid', models.CharField(db_index=True, max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Third gender')], null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('app_created_at', models.DateTimeField(blank=True, null=True)),
                ('app_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('educational_qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='family_educational_qualification', to='master_data.masterlookup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('monthly_average_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monthly_average_income', to='master_data.masterlookup')),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occupation', to='master_data.masterlookup')),
                ('relationship_to_respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relationship_to_respondent', to='master_data.masterlookup')),
            ],
            options={
                'verbose_name_plural': 'Family Members',
            },
        ),
    ]
