# Generated by Django 4.2.1 on 2023-08-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0031_donor_code'),
        ('sims', '0051_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='cough_for_more_than_two_weeks',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='dosage_of_insulin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='duration_since_last_meal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='family_history_of_diabetes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='family_history_of_diabetes', to='master_data.masterlookup'),
        ),
        migrations.AddField(
            model_name='screening',
            name='fever_for_more_than_2_weeks',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='have_you_attended_awarness_training',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='insulin_dependent_or_non_insulin_dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insulin_dependent_or_non_insulin_dependent', to='master_data.masterlookup'),
        ),
        migrations.AddField(
            model_name='screening',
            name='medication_hypertension',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='night_sweats',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='physical_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='physical_activity', to='master_data.masterlookup'),
        ),
        migrations.AddField(
            model_name='screening',
            name='unexplained_weight_loss_or_loss_of_appetite',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='waist_circumference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='waist_circumference', to='master_data.masterlookup'),
        ),
        migrations.AddField(
            model_name='screening',
            name='which_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='which_training', to='master_data.masterlookup'),
        ),
    ]
