# Generated by Django 4.2.1 on 2023-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0052_screening_cough_for_more_than_two_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='when_was_it_diagnosed_number_of_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='when_was_it_diagnosed_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
