# Generated by Django 4.2.1 on 2023-08-16 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0031_donor_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sims', '0053_screening_when_was_it_diagnosed_number_of_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('range_from', models.CharField(blank=True, max_length=255, null=True)),
                ('range_to', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
