# Generated by Django 4.2.1 on 2023-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0054_qrcodegeneration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodegeneration',
            options={'verbose_name_plural': 'QR Code Generation'},
        ),
        migrations.AddField(
            model_name='patient',
            name='qr_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
