# Generated by Django 4.2.1 on 2023-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0056_alter_qrcodegeneration_range_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='feedback',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
