# Generated by Django 4.2.1 on 2023-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0057_patient_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='partner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familymember',
            name='vision_center_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glassprescription',
            name='partner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glassprescription',
            name='vision_center_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='partner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='vision_center_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screening',
            name='partner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screening',
            name='vision_center_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spectacletype',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spectacletype',
            name='partner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visualacuity',
            name='partner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visualacuity',
            name='vision_center_id',
            field=models.IntegerField(default=0),
        ),
    ]
