# Generated by Django 4.2.1 on 2023-09-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0059_rename_follow_up_status_spectacletype_spectacle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='courier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='invoice_value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
