# Generated by Django 4.2.1 on 2023-09-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0039_otpverificationdetails'),
        ('sims', '0061_camp_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='exclusive_camp',
            field=models.IntegerField(choices=[(1, 'YES'), (2, 'NO')], default=1),
        ),
        migrations.AddField(
            model_name='camp',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.partner'),
        ),
    ]
