# Generated by Django 4.2.1 on 2023-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0063_glassprescription_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectacletype',
            name='r2c_eligible',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (2, 'NO')], null=True),
        ),
        migrations.AddField(
            model_name='spectacletype',
            name='r2c_remark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
