# Generated by Django 4.2.1 on 2023-11-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0065_camp_end_time_camp_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='start_time',
        ),
    ]
