# Generated by Django 4.2.1 on 2023-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0066_remove_camp_end_time_remove_camp_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
