# Generated by Django 4.2.1 on 2023-12-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0043_alter_partner_code'),
        ('sims', '0067_camp_end_time_camp_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='code_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_description', to='master_data.masterlookup'),
        ),
    ]
