# Generated by Django 4.2.1 on 2023-12-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0068_alter_screening_code_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='partner_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='vision_center_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
