# Generated by Django 4.2.1 on 2023-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0069_alter_camp_status_alter_cataractquestions_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='cataractquestions',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='glassprescription',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='orderdeliverydetails',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='orderrequestdetails',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='qrcodegeneration',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='screening',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='spectacletype',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='tellicallingquestionsandanswers',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='visualacuity',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
    ]
