# Generated by Django 4.2.1 on 2023-12-10 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sims', '0070_alter_camp_status_alter_cataractquestions_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='approved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
