# Generated by Django 4.2.1 on 2023-12-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0069_alter_familymember_name_and_more'),
        ('sims', '0071_patient_approved_by_patient_approved_on_and_more'),
    ]

    operations = [
    ]
