# Generated by Django 4.2.1 on 2023-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0072_merge_20231211_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='model_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='patient_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
