# Generated by Django 4.2.1 on 2023-12-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0073_familymember_model_type_familymember_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='ssmis_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
