# Generated by Django 5.0 on 2023-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0074_camp_ssmis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodegeneration',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
