# Generated by Django 4.2.1 on 2023-12-28 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0048_district_ssmis_id_donor_ssmis_id_partner_ssmis_id_and_more'),
        ('sims', '0076_patient_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('sync_status', models.PositiveIntegerField(default=2)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_of_patients_syn', models.IntegerField(default=0)),
                ('no_of_patients_not_syn', models.IntegerField(default=0)),
                ('not_syn_patients_ids', models.TextField(blank=True, null=True)),
                ('no_of_screening_syn', models.IntegerField(default=0)),
                ('no_of_screening_not_syn', models.IntegerField(default=0)),
                ('not_syn_screening_ids', models.TextField(blank=True, null=True)),
                ('no_of_family_member_syn', models.IntegerField(default=0)),
                ('no_of_family_member_not_syn', models.IntegerField(default=0)),
                ('not_syn_family_member_ids', models.TextField(blank=True, null=True)),
                ('no_of_visual_acuity_syn', models.IntegerField(default=0)),
                ('no_of_visual_acuity_not_syn', models.IntegerField(default=0)),
                ('not_syn_visual_acuity_ids', models.TextField(blank=True, null=True)),
                ('no_of_glass_prescription_syn', models.IntegerField(default=0)),
                ('no_of_glass_prescription_not_syn', models.IntegerField(default=0)),
                ('not_syn_glass_prescription_ids', models.TextField(blank=True, null=True)),
                ('no_of_spectacle_type_syn', models.IntegerField(default=0)),
                ('no_of_spectacle_type_not_syn', models.IntegerField(default=0)),
                ('not_syn_spectacle_type_ids', models.TextField(blank=True, null=True)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sims.camp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('hospital_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.partner')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('vision_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.visioncenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
