# Generated by Django 4.2.1 on 2023-12-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0077_datafreeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='data_freeze_status',
            field=models.IntegerField(choices=[(1, 'Synced'), (2, 'Not Synced')], default=2),
        ),
    ]
