# Generated by Django 5.0 on 2023-12-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0079_familymember_data_freeze_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='data_freeze_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Synced'), (2, 'Not Synced')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='glassprescription',
            name='data_freeze_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Synced'), (2, 'Not Synced')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='data_freeze_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Synced'), (2, 'Not Synced')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='data_freeze_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Synced'), (2, 'Not Synced')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='spectacletype',
            name='data_freeze_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Synced'), (2, 'Not Synced')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='visualacuity',
            name='data_freeze_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Synced'), (2, 'Not Synced')], default=2, null=True),
        ),
    ]
