# Generated by Django 5.0 on 2024-01-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0080_alter_familymember_data_freeze_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataractquestions',
            name='call_disposition_group',
            field=models.IntegerField(blank=True, choices=[(1, 'Complaint'), (2, 'Retry'), (3, 'Successful'), (4, 'UnSuccessful'), (5, 'Spectacle out of stock')], null=True),
        ),
        migrations.AlterField(
            model_name='tellicallingquestionsandanswers',
            name='call_disposition_group',
            field=models.IntegerField(blank=True, choices=[(1, 'Complaint'), (2, 'Retry'), (3, 'Successful'), (4, 'UnSuccessful'), (5, 'Spectacle out of stock')], null=True),
        ),
    ]
