# Generated by Django 5.0 on 2024-03-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0059_dailyrecordscalculation_uuid'),
        ('sims', '0081_alter_cataractquestions_call_disposition_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.district'),
        ),
    ]
