# Generated by Django 5.0 on 2024-04-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0061_visioncenter_address_alter_partner_address'),
        ('sims', '0083_receivedsms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedsms',
            name='languege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.language'),
        ),
        migrations.AlterField(
            model_name='receivedsms',
            name='spect_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
