# Generated by Django 5.0 on 2024-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0084_alter_receivedsms_languege_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedsms',
            name='mobile_no',
            field=models.CharField(max_length=12),
        ),
    ]
