# Generated by Django 4.2.1 on 2024-04-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0085_alter_receivedsms_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedsms',
            name='last_attempt_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivedsms',
            name='no_of_times_attempt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
