# Generated by Django 4.2.1 on 2024-04-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0086_receivedsms_last_attempt_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedsms',
            name='spect_status',
        ),
    ]
