# Generated by Django 4.2.1 on 2024-04-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0087_remove_receivedsms_spect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedsms',
            name='error_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsms',
            name='sms_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
