# Generated by Django 4.2.1 on 2023-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_district_name_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.IntegerField(choices=[(1, 'Web'), (2, 'App'), (3, 'Both')]),
        ),
    ]
