# Generated by Django 4.2.1 on 2023-06-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_alter_role_role_type_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
