# Generated by Django 4.2.1 on 2023-06-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorPartnerRelation',
        ),
    ]
