# Generated by Django 4.2.1 on 2023-06-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_donorpartnerrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='district',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='DonorPartnerRelation',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
