# Generated by Django 4.2.1 on 2023-07-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_uservendorlinkage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVendorLinkage',
        ),
    ]
