# Generated by Django 4.2.1 on 2023-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_partnervendorlinkage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservendorlinkage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='uservendorlinkage',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='uservendorlinkage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservendorlinkage',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='PartnerVendorLinkage',
        ),
        migrations.DeleteModel(
            name='UserVendorLinkage',
        ),
    ]
