# Generated by Django 4.2.1 on 2023-07-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_uservisioncenterlinkage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visioncenter',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.district'),
        ),
    ]
