# Generated by Django 4.2.1 on 2023-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_rename_slug_masterlookup_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlookup',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
