# Generated by Django 4.2.1 on 2023-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_alter_masterlookup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='donor',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='donorpartnerlinkage',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='partner',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='partnervendorlinkage',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='role',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='state',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='telecalling',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userpartnerlinkage',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='uservendorlinkage',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='uservisioncenterlinkage',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='visioncenter',
            name='sync_status',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
