# Generated by Django 4.2.1 on 2023-07-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_alter_donorpartnerlinkage_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorpartnerlinkage',
            name='donor',
        ),
        migrations.AddField(
            model_name='donorpartnerlinkage',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.donor'),
        ),
    ]
