# Generated by Django 4.2.1 on 2023-07-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_remove_donorpartnerlinkage_donor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.district'),
        ),
    ]
