# Generated by Django 4.2.1 on 2023-07-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_alter_partner_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='district',
        ),
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.state'),
        ),
    ]
