# Generated by Django 4.2.1 on 2023-07-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0028_remove_partner_district_partner_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visioncenter',
            name='district',
        ),
    ]
