# Generated by Django 4.2.1 on 2023-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_remove_visioncenter_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
