# Generated by Django 4.2.1 on 2023-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_role_role_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='code',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
