# Generated by Django 4.2.1 on 2023-08-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0032_config'),
        ('master_data', '0032_state_code'),
    ]

    operations = [
    ]
