# Generated by Django 4.2.1 on 2023-08-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0033_merge_0032_config_0032_state_code'),
        ('master_data', '0034_applicationuserstatelinkage'),
    ]

    operations = [
    ]
