# Generated by Django 4.2.1 on 2023-09-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0035_merge_20230825_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
