# Generated by Django 4.2.1 on 2023-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0037_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='otp_verification',
            field=models.IntegerField(choices=[(1, 'Not Required'), (2, 'Required')], default=2),
        ),
    ]
