# Generated by Django 4.2.1 on 2023-11-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0041_alter_dailyrecordscalculation_not_saved_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
