# Generated by Django 4.2.1 on 2023-11-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0042_alter_partner_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
