# Generated by Django 4.2.1 on 2023-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0044_alter_applicationuserstatelinkage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuserstatelinkage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='config',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='dailyrecordscalculation',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='district',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='donorpartnerlinkage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='language',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='masterlookup',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='otpverificationdetails',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='partnervendorlinkage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='telecalling',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='userpartnerlinkage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='uservendorlinkage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='uservisioncenterlinkage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='visioncenter',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='zone',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], db_index=True, default=2),
        ),
    ]
