# Generated by Django 4.2.1 on 2023-12-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0045_alter_applicationuserstatelinkage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordscalculation',
            name='error',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
