# Generated by Django 5.0 on 2023-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0048_district_ssmis_id_donor_ssmis_id_partner_ssmis_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='alternative_email_id_1',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='alternative_email_id_2',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='alternative_email_id_3',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='alternative_email_id_4',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
