# Generated by Django 4.2.1 on 2024-01-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0049_vendor_alternative_email_id_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverificationdetails',
            name='no_of_verified',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
