# Generated by Django 4.2.1 on 2024-01-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0051_userdonorlinkage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdonorlinkage',
            options={'verbose_name_plural': 'User Donor Linkage'},
        ),
    ]
