# Generated by Django 5.0 on 2024-02-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0055_cronjobsummarylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visioncenter',
            name='vc_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Mobile vc'), (2, 'Static vc')], null=True),
        ),
    ]
