# Generated by Django 5.0 on 2024-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0056_visioncenter_vc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjobsummarylog',
            name='error',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
