# Generated by Django 5.0 on 2024-03-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0057_cronjobsummarylog_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobsummarylog',
            name='most_recent_update_time_taken_millis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
