# Generated by Django 5.0 on 2024-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0058_alter_cronjobsummarylog_most_recent_update_time_taken_millis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordscalculation',
            name='uuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
