# Generated by Django 5.0 on 2024-03-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0059_dailyrecordscalculation_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visioncenter',
            name='address',
        ),
    ]
