# Generated by Django 5.0 on 2024-03-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0060_remove_visioncenter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='visioncenter',
            name='address',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
